## Data Cleaning

In [1]:
# imports
import pandas as pd

In [2]:
# reading the data
data_2022 = pd.read_csv("data_22.csv")
data_2023 = pd.read_csv("data_23.csv")
data_2024 = pd.read_csv("data_24.csv")

### 2022 Data

In [3]:
# look at number of rows and columns
data_2022.shape

(646, 17)

In [4]:
# list all columns
data_2022.columns.tolist()

['uri',
 'artist_names',
 'track_name',
 'peak_rank',
 'weeks_on_chart',
 'danceability',
 'energy',
 'key',
 'loudness',
 'mode',
 'speechiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'tempo',
 'time_signature',
 'duration_ms']

In [5]:
# keep only required columns
data_2022 = data_2022[[
    "uri",
    "track_name",
    "artist_names",
    "peak_rank",
    "weeks_on_chart",
    "danceability",
    "energy",
    "key",
    "loudness",
    "mode",
    "speechiness",
    "acousticness",
    "tempo"
]]

In [6]:
# look at the dataset high-level
data_2022.head()

,uri,track_name,artist_names,peak_rank,weeks_on_chart,danceability,energy,key,loudness,mode,speechiness,acousticness,tempo
0,spotify:track:02MWAaffLxlfxAUY7c5dvx,Heat Waves,Glass Animals,1,65,0.761,0.525,11,-6.900,1,0.0944,0.4400,80.870
1,spotify:track:5PjdY0CKGZdEuoNab3yDmX,STAY (with Justin Bieber),"The Kid LAROI, Justin Bieber",1,37,0.591,0.764,1,-5.484,1,0.0483,0.0383,169.928
2,spotify:track:3IAfUEeaXRX9s9UdKOJrFI,Envolver,Anitta,3,3,0.812,0.736,4,-5.421,0,0.0833,0.1520,91.993
3,spotify:track:1HhNoOuqm1a5MXYEgAFl8o,Enemy (with JID) - from the series Arcane Leag...,"Imagine Dragons, JID, Arcane, League of Legends",3,21,0.728,0.783,11,-4.424,0,0.2660,0.2370,77.011
4,spotify:track:4fouWK6XVHhzl78KzQ1UjL,abcdefu,GAYLE,1,19,0.695,0.540,4,-5.692,1,0.0493,0.2990,121.932

In [7]:
# check data types and if null values are allowed
data_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 646 entries, 0 to 645
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   uri             646 non-null    str
 1   track_name      646 non-null    str
 2   artist_names    646 non-null    str
 3   peak_rank       646 non-null    int64
 4   weeks_on_chart  646 non-null    int64
 5   danceability    646 non-null    float64
 6   energy          646 non-null    float64
 7   key             646 non-null    int64
 8   loudness        646 non-null    float64
 9   mode            646 non-null    int64
 10  speechiness     646 non-null    float64
 11  acousticness    646 non-null    float64
 12  tempo           646 non-null    float64
dtypes: float64(6), int64(4), str(3)
memory usage: 108.9 KB

In [8]:
# null values are not allowed but to check
data_2022.isnull().sum()

uri               0
track_name        0
artist_names      0
peak_rank         0
weeks_on_chart    0
danceability      0
energy            0
key               0
loudness          0
mode              0
speechiness       0
acousticness      0
tempo             0
dtype: int64

#### standardising 2022 data types

In [9]:
# Clean text columns
text_cols_2022 = ["uri", "artist_names", "track_name"]

for col in text_cols_2022:
    data_2022[col] = data_2022[col].astype("string")

# Integer columns
int_cols_2022 = ["peak_rank", "weeks_on_chart", "key", "mode",]

for col in int_cols_2022:
    data_2022[col] = pd.to_numeric(data_2022[col], errors="coerce").astype("Int64")

# Float columns
float_cols_2022 = ["danceability", "energy", "loudness", "speechiness", "acousticness", "tempo"]

for col in float_cols_2022:
    data_2022[col] = pd.to_numeric(data_2022[col], errors="coerce")

# give key numbers their actual key values
key_map = {
0:"C",1:"C#",2:"D",3:"D#",4:"E",
5:"F",6:"F#",7:"G",8:"G#",9:"A",10:"A#",11:"B"
}

data_2022["key"] = data_2022["key"].map(key_map)

# same for Major or Minor
mode_map = {1:"Major",0:"Minor"}
data_2022["mode"] = data_2022["mode"].map(mode_map)

# convert them into string
data_2022["key"] = data_2022["key"].astype("string")
data_2022["mode"] = data_2022["mode"].astype("string")

# Check result
data_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 646 entries, 0 to 645
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   uri             646 non-null    string
 1   track_name      646 non-null    string
 2   artist_names    646 non-null    string
 3   peak_rank       646 non-null    Int64
 4   weeks_on_chart  646 non-null    Int64
 5   danceability    646 non-null    float64
 6   energy          646 non-null    float64
 7   key             646 non-null    string
 8   loudness        646 non-null    float64
 9   mode            646 non-null    string
 10  speechiness     646 non-null    float64
 11  acousticness    646 non-null    float64
 12  tempo           646 non-null    float64
dtypes: Int64(2), float64(6), string(5)
memory usage: 114.4 KB

### 2023 Data

In [10]:
# repeat the same process for 2023 dataset
data_2023.shape

(953, 24)

In [11]:
# check columns
data_2023.columns.tolist()

['track_name',
 'artist(s)_name',
 'artist_count',
 'released_year',
 'released_month',
 'released_day',
 'in_spotify_playlists',
 'in_spotify_charts',
 'streams',
 'in_apple_playlists',
 'in_apple_charts',
 'in_deezer_playlists',
 'in_deezer_charts',
 'in_shazam_charts',
 'bpm',
 'key',
 'mode',
 'danceability_%',
 'valence_%',
 'energy_%',
 'acousticness_%',
 'instrumentalness_%',
 'liveness_%',
 'speechiness_%']

In [12]:
# remove columns which are not required, keep only required
data_2023 = data_2023[[
    "track_name",
    "artist(s)_name",
    "streams",
    "bpm",
    "key",
    "mode",
    "danceability_%",
    "valence_%",
    "energy_%",
    "acousticness_%",
    "instrumentalness_%",
    "liveness_%",
    "speechiness_%"
]]

In [13]:
data_2023.head()

,track_name,artist(s)_name,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",141381703,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,133716286,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,140003974,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,800840817,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,303236322,144,A,Minor,65,23,80,14,63,11,6

In [14]:
data_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_name          953 non-null    str
 1   artist(s)_name      953 non-null    str
 2   streams             953 non-null    str
 3   bpm                 953 non-null    int64
 4   key                 858 non-null    str
 5   mode                953 non-null    str
 6   danceability_%      953 non-null    int64
 7   valence_%           953 non-null    int64
 8   energy_%            953 non-null    int64
 9   acousticness_%      953 non-null    int64
 10  instrumentalness_%  953 non-null    int64
 11  liveness_%          953 non-null    int64
 12  speechiness_%       953 non-null    int64
dtypes: int64(8), str(5)
memory usage: 143.1 KB

In [15]:
data_2023.isnull().sum()

track_name             0
artist(s)_name         0
streams                0
bpm                    0
key                   95
mode                   0
danceability_%         0
valence_%              0
energy_%               0
acousticness_%         0
instrumentalness_%     0
liveness_%             0
speechiness_%          0
dtype: int64

#### standardize 2023 data types

In [20]:
# Rename artist column to match other datasets
data_2023 = data_2023.rename(columns={
    "artist(s)_name": "artist_names"
})

# Clean text columns
text_cols_2023 = ["track_name", "artist_names", "key", "mode"]

for col in text_cols_2023:
    data_2023[col] = data_2023[col].astype("string")

# Clean and convert streams safely
data_2023["streams"] = (
    data_2023["streams"]
    .astype("string")
    .str.replace(",", "", regex=False)
    .str.strip()
)

data_2023["streams"] = pd.to_numeric(data_2023["streams"], errors="coerce")

# Drop rows where streams is invalid/missing
data_2023 = data_2023.dropna(subset=["streams"])

# Now convert to integer
data_2023["streams"] = data_2023["streams"].astype("int64")

# Numeric columns
numeric_cols_2023 = [
    "bpm",
    "danceability_%",
    "valence_%",
    "energy_%",
    "acousticness_%",
    "instrumentalness_%",
    "liveness_%",
    "speechiness_%"
]

for col in numeric_cols_2023:
    data_2023[col] = pd.to_numeric(data_2023[col], errors="coerce")

# Convert percentage columns to decimals to match 2022 dataset
cols_pct = [
    "danceability_%",
    "valence_%",
    "energy_%",
    "acousticness_%",
    "instrumentalness_%",
    "liveness_%",
    "speechiness_%"
]

data_2023[cols_pct] = data_2023[cols_pct] / 100

# Rename columns so they match 2022 naming
data_2023 = data_2023.rename(columns={
    "danceability_%": "danceability",
    "valence_%": "valence",
    "energy_%": "energy",
    "acousticness_%": "acousticness",
    "instrumentalness_%": "instrumentalness",
    "liveness_%": "liveness",
    "speechiness_%": "speechiness"
})

# Keep key and mode as cleaned text
data_2023["key"] = data_2023["key"].replace("nan", pd.NA)
data_2023["mode"] = data_2023["mode"].replace("nan", pd.NA)

# Check result
data_2023.info()

<class 'pandas.DataFrame'>
Index: 952 entries, 0 to 952
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_name        952 non-null    string
 1   artist_names      952 non-null    string
 2   streams           952 non-null    int64
 3   bpm               952 non-null    int64
 4   key               857 non-null    string
 5   mode              952 non-null    string
 6   danceability      952 non-null    float64
 7   valence           952 non-null    float64
 8   energy            952 non-null    float64
 9   acousticness      952 non-null    float64
 10  instrumentalness  952 non-null    float64
 11  liveness          952 non-null    float64
 12  speechiness       952 non-null    float64
dtypes: float64(7), int64(2), string(4)
memory usage: 142.2 KB

#### Fix the 2023 artist column name so it matches too

In [21]:
data_2023 = data_2023.rename(columns={
    "artist(s)_name": "artist_names"
})

data_2023.columns

Index(['track_name', 'artist_names', 'streams', 'bpm', 'key', 'mode',
       'danceability', 'valence', 'energy', 'acousticness', 'instrumentalness',
       'liveness', 'speechiness'],
      dtype='str')

### 2024 Data

In [22]:
data_2024.shape

(4600, 29)

In [23]:
data_2024.columns.tolist()

['Track',
 'Album Name',
 'Artist',
 'Release Date',
 'ISRC',
 'All Time Rank',
 'Track Score',
 'Spotify Streams',
 'Spotify Playlist Count',
 'Spotify Playlist Reach',
 'Spotify Popularity',
 'YouTube Views',
 'YouTube Likes',
 'TikTok Posts',
 'TikTok Likes',
 'TikTok Views',
 'YouTube Playlist Reach',
 'Apple Music Playlist Count',
 'AirPlay Spins',
 'SiriusXM Spins',
 'Deezer Playlist Count',
 'Deezer Playlist Reach',
 'Amazon Playlist Count',
 'Pandora Streams',
 'Pandora Track Stations',
 'Soundcloud Streams',
 'Shazam Counts',
 'TIDAL Popularity',
 'Explicit Track']

In [24]:
data_2024 = data_2024[[
    "Track",
    "Artist",
    "Spotify Streams",
    "ISRC",
    "All Time Rank",
    "Track Score"
]]

In [25]:
data_2024.head()

,Track,Artist,Spotify Streams,ISRC,All Time Rank,Track Score
0,MILLION DOLLAR BABY,Tommy Richman,"390,470,936",QM24S2402528,1,725.4
1,Not Like Us,Kendrick Lamar,"323,703,884",USUG12400910,2,545.9
2,i like the way you kiss me,Artemas,"601,309,283",QZJ842400387,3,538.4
3,Flowers,Miley Cyrus,"2,031,280,633",USSM12209777,4,444.9
4,Houdini,Eminem,"107,034,922",USUG12403398,5,423.3

In [26]:
data_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Track            4600 non-null   str
 1   Artist           4595 non-null   str
 2   Spotify Streams  4487 non-null   str
 3   ISRC             4600 non-null   str
 4   All Time Rank    4600 non-null   str
 5   Track Score      4600 non-null   float64
dtypes: float64(1), str(5)
memory usage: 461.5 KB

In [27]:
data_2024.isnull().sum()

Track                0
Artist               5
Spotify Streams    113
ISRC                 0
All Time Rank        0
Track Score          0
dtype: int64

#### Standardize column names in the 2024 dataset

In [28]:
data_2024.columns = (
    data_2024.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

data_2024.columns

Index(['track', 'artist', 'spotify_streams', 'isrc', 'all_time_rank',
       'track_score'],
      dtype='str')

#### Rename the key identity columns in 2024 to match the other datasets

In [29]:
data_2024 = data_2024.rename(columns={
    "track": "track_name",
    "artist": "artist_names"
})

data_2024.columns

Index(['track_name', 'artist_names', 'spotify_streams', 'isrc',
       'all_time_rank', 'track_score'],
      dtype='str')

In [30]:
data_2024.dtypes

track_name             str
artist_names           str
spotify_streams        str
isrc                   str
all_time_rank          str
track_score        float64
dtype: object

#### Convert spotify_streams and the other major numeric columns to a real numeric column

In [32]:
# Clean text columns
text_cols_2024 = ["track_name", "artist_names", "isrc"]

for col in text_cols_2024:
    data_2024[col] = data_2024[col].astype("string")

# Clean and convert spotify_streams safely
data_2024["spotify_streams"] = (
    data_2024["spotify_streams"]
    .astype("string")
    .str.replace(",", "", regex=False)
    .str.strip()
)

data_2024["spotify_streams"] = pd.to_numeric(data_2024["spotify_streams"], errors="coerce")

# Drop rows where spotify_streams is invalid/missing
data_2024 = data_2024.dropna(subset=["spotify_streams"])

# Convert spotify_streams to integer
data_2024["spotify_streams"] = data_2024["spotify_streams"].astype("int64")

# Convert remaining numeric columns
data_2024["all_time_rank"] = pd.to_numeric(data_2024["all_time_rank"], errors="coerce").astype("Int64")
data_2024["track_score"] = pd.to_numeric(data_2024["track_score"], errors="coerce")

# Check result
data_2024.info()

<class 'pandas.DataFrame'>
Index: 4487 entries, 0 to 4599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   track_name       4487 non-null   string
 1   artist_names     4487 non-null   string
 2   spotify_streams  4487 non-null   int64
 3   isrc             4487 non-null   string
 4   all_time_rank    976 non-null    Int64
 5   track_score      4487 non-null   float64
dtypes: Int64(1), float64(1), int64(1), string(3)
memory usage: 423.9 KB

#### Check missing values in the key columns for all 3 datasets

In [33]:
print("2022")
print(data_2022[["track_name", "artist_names"]].isna().sum())

print("\n2023")
print(data_2023[["track_name", "artist_names"]].isna().sum())

print("\n2024")
print(data_2024[["track_name", "artist_names"]].isna().sum())

2022
track_name      0
artist_names    0
dtype: int64

2023
track_name      0
artist_names    0
dtype: int64

2024
track_name      0
artist_names    0
dtype: int64

In [34]:
data_2024[data_2024["artist_names"].isna()][["track_name", "isrc"]]

Empty DataFrame
Columns: [track_name, isrc]
Index: []

In [35]:
data_2024 = data_2024.dropna(subset=["artist_names"])
data_2024[["track_name", "artist_names"]].isna().sum()

track_name      0
artist_names    0
dtype: int64

#### Standardize text formatting for song and artist names
- remove leading/trailing spaces
- convert to lowercase
- remove double spaces

In [36]:
def clean_text(series):
    return (
        series.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

data_2022["track_name"] = clean_text(data_2022["track_name"])
data_2022["artist_names"] = clean_text(data_2022["artist_names"])

data_2023["track_name"] = clean_text(data_2023["track_name"])
data_2023["artist_names"] = clean_text(data_2023["artist_names"])

data_2024["track_name"] = clean_text(data_2024["track_name"])
data_2024["artist_names"] = clean_text(data_2024["artist_names"])

#### Check for duplicate songs now that names are cleaned

In [37]:
print("2022 duplicates:", data_2022.duplicated(subset=["track_name", "artist_names"]).sum())
print("2023 duplicates:", data_2023.duplicated(subset=["track_name", "artist_names"]).sum())
print("2024 duplicates:", data_2024.duplicated(subset=["track_name", "artist_names"]).sum())

2022 duplicates: 1
2023 duplicates: 4
2024 duplicates: 100

In [38]:
data_2022[data_2022.duplicated(subset=["track_name", "artist_names"], keep=False)] \
    .sort_values(["track_name", "artist_names"])

,uri,track_name,artist_names,peak_rank,weeks_on_chart,danceability,energy,key,loudness,mode,speechiness,acousticness,tempo
164,spotify:track:4UPQiDmYScn2C6S2C2WATY,just a cloud away,pharrell williams,165,1,0.888,0.459,D,-8.154,Major,0.0357,0.426,112.560
404,spotify:track:0DGTcMqvVR7fmBXgiG6jz4,just a cloud away,pharrell williams,115,2,0.890,0.460,D,-8.155,Major,0.0359,0.432,112.555

In [39]:
data_2023[data_2023.duplicated(subset=["track_name", "artist_names"], keep=False)] \
    .sort_values(["track_name", "artist_names"])

,track_name,artist_names,streams,bpm,key,mode,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness
372,about damn time,lizzo,723894473,109,A#,Minor,0.84,0.72,0.74,0.10,0.00,0.34,0.07
764,about damn time,lizzo,723894473,109,A#,Minor,0.84,0.72,0.74,0.10,0.00,0.34,0.07
178,snap,rosa linn,726307468,170,<NA>,Major,0.56,0.53,0.64,0.11,0.00,0.45,0.06
873,snap,rosa linn,711366595,170,<NA>,Major,0.56,0.52,0.64,0.11,0.00,0.45,0.07
345,spit in my face!,thxsomch,303216294,94,G#,Major,0.73,0.65,0.79,0.05,0.02,0.11,0.06
482,spit in my face!,thxsomch,301869854,166,C#,Major,0.70,0.57,0.57,0.09,0.20,0.11,0.07
512,take my breath,the weeknd,130655803,121,A#,Minor,0.70,0.35,0.77,0.01,0.00,0.26,0.04
616,take my breath,the weeknd,432702334,121,G#,Major,0.75,0.53,0.74,0.02,0.00,0.11,0.05

In [40]:
data_2024[data_2024.duplicated(subset=["track_name", "artist_names"], keep=False)] \
    .sort_values(["track_name", "artist_names"])

,track_name,artist_names,spotify_streams,isrc,all_time_rank,track_score
1350,24k magic,bruno mars,1425996809,USAT21602944,<NA>,40.6
1889,24k magic,bruno mars,1425996809,USAT21603246,<NA>,33.5
36,a bar song (tipsy),shaboozey,311928522,USUYG1541249,37,226.4
395,a bar song (tipsy),shaboozey,311928522,USUYG1543926,395,76.8
171,about damn time,lizzo,847025688,USAT22202139,172,115.6
...,...,...,...,...,...,...
3374,"young, wild & free (feat. bruno mars)",snoop dogg,1431126152,USAT21102233,<NA>,23.7
3696,"young, wild & free (feat. bruno mars)",snoop dogg,1431126152,USAT21102232,<NA>,22.4
1645,ýýýýýý,yoasobi,84848838,JPP302300523,<NA>,36.1
2880,ýýýýýý,yoasobi,311307250,JPP302000760,<NA>,26.1
4279,ýýýýýý,yoasobi,140194014,JPP302200613,<NA>,20.4

In [41]:
data_2022 = data_2022.drop_duplicates(subset=["track_name", "artist_names"], keep="first")
data_2023 = data_2023.drop_duplicates(subset=["track_name", "artist_names"], keep="first")
data_2024 = data_2024.drop_duplicates(subset=["track_name", "artist_names"], keep="first")

In [42]:
data_2022[data_2022.duplicated(subset=["track_name", "artist_names"], keep=False)] \
    .sort_values(["track_name", "artist_names"])

Empty DataFrame
Columns: [uri, track_name, artist_names, peak_rank, weeks_on_chart, danceability, energy, key, loudness, mode, speechiness, acousticness, tempo]
Index: []

In [43]:
data_2023[data_2023.duplicated(subset=["track_name", "artist_names"], keep=False)] \
    .sort_values(["track_name", "artist_names"])

Empty DataFrame
Columns: [track_name, artist_names, streams, bpm, key, mode, danceability, valence, energy, acousticness, instrumentalness, liveness, speechiness]
Index: []

In [44]:
data_2024[data_2024.duplicated(subset=["track_name", "artist_names"], keep=False)] \
    .sort_values(["track_name", "artist_names"])

Empty DataFrame
Columns: [track_name, artist_names, spotify_streams, isrc, all_time_rank, track_score]
Index: []

In [45]:
print("2022 duplicates:", data_2022.duplicated(subset=["track_name", "artist_names"]).sum())
print("2023 duplicates:", data_2023.duplicated(subset=["track_name", "artist_names"]).sum())
print("2024 duplicates:", data_2024.duplicated(subset=["track_name", "artist_names"]).sum())

2022 duplicates: 0
2023 duplicates: 0
2024 duplicates: 0

In [46]:
print("2022 missing values:")
print(data_2022.isnull().sum())

print("\n2023 missing values:")
print(data_2023.isnull().sum())

print("\n2024 missing values:")
print(data_2024.isnull().sum())

2022 missing values:
uri               0
track_name        0
artist_names      0
peak_rank         0
weeks_on_chart    0
danceability      0
energy            0
key               0
loudness          0
mode              0
speechiness       0
acousticness      0
tempo             0
dtype: int64

2023 missing values:
track_name           0
artist_names         0
streams              0
bpm                  0
key                 94
mode                 0
danceability         0
valence              0
energy               0
acousticness         0
instrumentalness     0
liveness             0
speechiness          0
dtype: int64

2024 missing values:
track_name            0
artist_names          0
spotify_streams       0
isrc                  0
all_time_rank      3425
track_score           0
dtype: int64

- For 2022 nothing is missing so it's ok
- For 2023, only `key` has missing values. key represents the musical key of the song (e.g., C#, A, D) and is not required for identifying songs or ranking popularity.
- For 2024, `all_time_rank` has missing values. all_time_rank is not required for identifying songs or performing audio feature comparisons. Dropping rows based on all_time_rank would remove a large portion of the dataset (over 70%), which would significantly reduce the dataset size and bias the analysis. Therefore, all_time_rank is kept as NULL where missing.

In [47]:
data_2024.shape

(4387, 6)

In [ ]:
data_2022.to_csv("cleaned_data_2022.csv", index=False)
data_2023.to_csv("cleaned_data_2023.csv", index=False)
data_2024.to_csv("cleaned_data_2024.csv", index=False)